### ISSUE TITLE
您好，请问如何使用自己的horizon来拍摄

### ISSUE THREAD

**Issue by SEU-zhc** [Livox-SDK/horizon_highway_slam#1]
readme中似乎只提供了打开rosbag样例的方式，请问如何运行程序拍摄自己的点云数据

**Comment by PanZhichen** [comment]
你好:
1.  如果您通过docker方式进行安装,请先将horizon_highway_slam.launch文件中的rosbag语句注释掉:
    ```
    <!-- <node pkg="rosbag" type="play" name="rosbag_play" output="screen" args="/root/shared_dir/$(arg BagName)"/> -->
    ```
2. 启动horizon_highway_slam:
    ```
    root@HOSTNAME:/# roslaunch horizon_highway_slam horizon_highway_slam.launch IMU:=2
    ```
    或者
    ```
    roslaunch horizon_highway_slam horizon_highway_slam_host.launch
    ```
3. 连接您的livox雷达,并启动livox_lidar_msg.launch,具体细节可参考[here](https://github.com/Livox-SDK/livox_ros_driver/blob/master/README_CN.md#%E8%A7%88%E6%B2%83-ros-%E9%A9%B1%E5%8A%A8%E7%A8%8B%E5%BA%8F-livox_ros_driver-english-readme-).
