### ISSUE TITLE
利用示例和horizon拍摄bag包，rviz播放视角漂移，而且lidar不动时，视角会自己高速移动，请问怎么解决

### ISSUE THREAD

**Issue by alsosos** [Livox-SDK/horizon_highway_slam#12]

**Comment by alsosos** [comment]
是否是雷达在初始化？

**Comment by alsosos** [comment]
When using the example and horizon to record a bag, the perspective of rviz is floating disorderly, and when lidar does not move, the perspective will move at a high speed. How can I solve this problem.

**Comment by Livox-SDK** [comment]
alsosos 你好~

建议先下载一下示例的点云包尝试运行一下程序. 看一下是否还有这种情况产生
