### ISSUE TITLE
 can not find libboost_system.so.1.58.0

### ISSUE THREAD

**Issue by narutojxl** [Livox-SDK/horizon_highway_slam#13]
Hi author, 
My OS is ubuntu18.04, i'm trying to run the demo following "Compile Method". When buiding it reminds some libs can not find.
>
	Scanning dependencies of target horizon_highway_mapping
	Scanning dependencies of target horizon_highway_odometry
	[ 25%] Building CXX object horizon_highway_slam/CMakeFiles/horizon_highway_mapping.dir/src/horizon_highway_mapping.cpp.o
	[ 50%] Building CXX object horizon_highway_slam/CMakeFiles/horizon_highway_odometry.dir/src/horizon_highway_odometry.cpp.o
	[ 75%] Linking CXX executable /home/jxl/horizon_ws/devel/lib/horizon_highway_slam/horizon_highway_mapping
	[100%] Linking CXX executable /home/jxl/horizon_ws/devel/lib/horizon_highway_slam/horizon_highway_odometry
	/usr/bin/ld: warning: libboost_system.so.1.58.0, needed by /home/jxl/horizon_ws/src/horizon_highway_slam/lib/libhorizon.so, not found (try using -rpath or -rpath-link)
	/usr/bin/ld: warning: libpcl_common.so.1.7, needed by /home/jxl/horizon_ws/src/horizon_highway_slam/lib/libhorizon.so, not found (try using -rpath or -rpath-link)
	/usr/bin/ld: warning: libpcl_kdtree.so.1.7, needed by /home/jxl/horizon_ws/src/horizon_highway_slam/lib/libhorizon.so, not found (try using -rpath or -rpath-link)
	/usr/bin/ld: warning: libpcl_filters.so.1.7, needed by /home/jxl/horizon_ws/src/horizon_highway_slam/lib/libhorizon.so, not found (try using -rpath or -rpath-link)
	/usr/bin/ld: warning: libpcl_segmentation.so.1.7, needed by /home/jxl/horizon_ws/src/horizon_highway_slam/lib/libhorizon.so, not found (try using -rpath or -rpath-link)
	/usr/bin/ld: warning: libcholmod.so.3.0.6, needed by /home/jxl/horizon_ws/src/horizon_highway_slam/lib/libhorizon.so, not found (try using -rpath or -rpath-link)
	[100%] Built target horizon_highway_mapping
	/usr/bin/ld: warning: libboost_system.so.1.58.0, needed by /home/jxl/horizon_ws/src/horizon_highway_slam/lib/libhorizon.so, not found (try using -rpath or -rpath-link)
	/usr/bin/ld: warning: libpcl_common.so.1.7, needed by /home/jxl/horizon_ws/src/horizon_highway_slam/lib/libhorizon.so, not found (try using -rpath or -rpath-link)
	/usr/bin/ld: warning: libpcl_kdtree.so.1.7, needed by /home/jxl/horizon_ws/src/horizon_highway_slam/lib/libhorizon.so, not found (try using -rpath or -rpath-link)
	/usr/bin/ld: warning: libpcl_filters.so.1.7, needed by /home/jxl/horizon_ws/src/horizon_highway_slam/lib/libhorizon.so, not found (try using -rpath or -rpath-link)
	/usr/bin/ld: warning: libpcl_segmentation.so.1.7, needed by /home/jxl/horizon_ws/src/horizon_highway_slam/lib/libhorizon.so, not found (try using -rpath or -rpath-link)
	/usr/bin/ld: warning: libcholmod.so.3.0.6, needed by /home/jxl/horizon_ws/src/horizon_highway_slam/lib/libhorizon.so, not found (try using -rpath or -rpath-link)
	[100%] Built target horizon_highway_odometry
	jxl@lenevo:~/horizon_ws$ 
I add libg2o.so path into system with `/etc/ld.so.conf.d/livox_horizon_highway_slam.conf` file, and then i launch `horizon_highway_slam_host.launch`, it reminds `horizon_highway_odometry` and `horizon_highway_mapping` can not find `libboost_system.so.1.58.0`, as `libhorizon.so` depends on them. Could you please give these libs in repository?  Can `horizon_highway_slam` run on ubuntu18.04? Thanks for your help!

**Comment by Livox-SDK** [comment]
Hi narutojxl,
  Since we built this code under Ubuntu 16.04, the directory may be different from Ubuntu 18.04. Please try the Docker method.

**Comment by csunking** [comment]
why not open source for project libhorizon and just use standard version of  g2o library ?
