### ISSUE TITLE
error while loading shared libraries: libg2o.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by gbfootball** [Livox-SDK/horizon_highway_slam#14]
my launch with this error

**error while loading shared libraries: libg2o.so: cannot open shared object file: No such file or directory**

**Comment by Livox-SDK** [comment]
Hi gbfootball 
Since we built this code under Ubuntu 16.04, the directory may be different from Ubuntu 18.04. 
Please try the Docker method.
