### ISSUE TITLE
Can not run slam

### ISSUE THREAD

**Issue by ZhenghaoSun** [Livox-SDK/horizon_highway_slam#3]
Hi, I got following error while running 

roslaunch horizon_highway_slam horizon_highway_slam.launch BagName:=xxx.bag IMU:=2

[ERROR] [1594985522.592475360]: Client [/horizon_highway_odometry] wants topic /livox/lidar to have datatype/md5sum [livox_ros_driver/CustomMsg/e4d6829bdfe657cb6c21a746c86b21a6], but our version has [sensor_msgs/PointCloud2/1158d486dd51d683ce2f1be655c3c181]. Dropping connection.

any hint to solve this problem?

**Comment by GraceMelon** [comment]
![image](https://user-images.githubusercontent.com/68271824/87893876-bf6f1780-ca73-11ea-9528-e25c948e22d4.png)
It seems you have the wrong LiDAR datatype.

**Comment by ZhenghaoSun** [comment]
> ![image](https://user-images.githubusercontent.com/68271824/87893876-bf6f1780-ca73-11ea-9528-e25c948e22d4.png)
> It seems you have the wrong LiDAR datatype.

Thanks, Grace. I saw the instruction but I recorded the .lvx file with the livox viewer. Then, I transfered the .lvx packet to rosbag using lvx_to_rosbag.launch. It seems there is nowhere to modify the data type of the message. Could u please explain more details?

**Comment by GraceMelon** [comment]
Do it in another way. Install livox_ros_driver first, then connect your Livox LiDAR with the PC, lastly use the following command:
roslaunch livox_ros_driver livox_lidar.launch
The driver will change Livox LiDAR from sensor_msgs/PointCloud2 to livox_ros_driver/CustomMsg.

**Comment by ZhenghaoSun** [comment]
> Do it in another way. Install livox_ros_driver first, then connect your Livox LiDAR with the PC, lastly use the following command:
> roslaunch livox_ros_driver livox_lidar.launch
> The driver will change Livox LiDAR from sensor_msgs/PointCloud2 to livox_ros_driver/CustomMsg.

Got it, thanks.
