### ISSUE TITLE
Download  YouTube_highway_demo.bag！！！

### ISSUE THREAD

**Issue by pangchenglin** [Livox-SDK/horizon_highway_slam#9]
if I want to download  YouTube_highway_demo.bag，some errors while happened like this：
![image](https://user-images.githubusercontent.com/30286312/95529998-2ff05980-0a0f-11eb-9c5e-ca6f01ae5b9c.png)
How to fix these problem？

**Comment by Livox-SDK** [comment]
please refer to this #6

**Comment by Livox-SDK** [comment]
#6
